# Generated by Django 2.0.5 on 2018-07-24 20:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='street Address')),
                ('city', models.CharField(max_length=75, verbose_name='city')),
                ('state', models.CharField(max_length=2, verbose_name='state')),
                ('zip_code', models.CharField(max_length=5, verbose_name='zip Code')),
            ],
        ),
        migrations.CreateModel(
            name='CapRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='capitalization Rate')),
                ('address', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='quotes.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing', models.PositiveIntegerField(verbose_name='marketing (annualized)')),
                ('taxes', models.PositiveIntegerField(verbose_name='taxes (annualized)')),
                ('insurance', models.PositiveIntegerField(verbose_name='insurance (annualized)')),
                ('repairs', models.PositiveIntegerField(verbose_name='repairs (annualized)')),
                ('administration', models.PositiveIntegerField(verbose_name='administration (annualized)')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quotes.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent', models.PositiveIntegerField(verbose_name='monthly Rent')),
                ('unit_number', models.CharField(max_length=10, verbose_name='unit Number')),
                ('vacancy', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='vacancy Rate (in whole numbers)')),
                ('bedrooms', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='bedrooms')),
                ('bathrooms', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='bathrooms')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Address')),
            ],
        ),
    ]
