# Generated by Django 2.0.5 on 2018-08-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='annual_unit_rent',
            field=models.PositiveIntegerField(default=0, verbose_name='annual Unit Rent'),
        ),
        migrations.AddField(
            model_name='result',
            name='annual_property_rent',
            field=models.PositiveIntegerField(default=0, verbose_name='annual Rent of Property'),
        ),
    ]
