# Generated by Django 2.0.5 on 2018-08-06 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_expense_annual_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Address'),
        ),
    ]
