# Generated by Django 2.0.5 on 2018-08-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20180806_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='debt_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='debt Rate'),
        ),
    ]
