# Generated by Django 2.0.5 on 2018-08-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_result_noi'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='debt_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='annual Debt Payment (NOI / 1.25)'),
        ),
        migrations.AddField(
            model_name='result',
            name='property_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='property Value'),
        ),
    ]
