# Generated by Django 2.0.5 on 2018-08-09 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_result_dscr_loan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quotes.Address'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street', 'city', 'state', 'zip_code')},
        ),
        migrations.AlterUniqueTogether(
            name='rent',
            unique_together={('address', 'monthly_rent', 'unit_number')},
        ),
    ]
