# Generated by Django 2.0.5 on 2018-08-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_auto_20180809_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='annual_expense',
            field=models.PositiveIntegerField(default=0, verbose_name='annual Expense'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='annual_unit_rent',
            field=models.PositiveIntegerField(default=0, verbose_name='annual Unit Rent'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='monthly_rent',
            field=models.PositiveIntegerField(verbose_name='monthly Rent'),
        ),
        migrations.AlterField(
            model_name='result',
            name='annual_property_rent',
            field=models.PositiveIntegerField(default=0, verbose_name='annual Rent of Property'),
        ),
        migrations.AlterField(
            model_name='result',
            name='debt_payment',
            field=models.IntegerField(default=0, verbose_name='annual Debt Payment (NOI / 1.25)'),
        ),
        migrations.AlterField(
            model_name='result',
            name='debt_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='debt Rate'),
        ),
        migrations.AlterField(
            model_name='result',
            name='dscr_loan_amount',
            field=models.IntegerField(default=0, verbose_name='Loan (DSCR approach)'),
        ),
        migrations.AlterField(
            model_name='result',
            name='loan_amount',
            field=models.IntegerField(default=0, verbose_name='loan Amount'),
        ),
        migrations.AlterField(
            model_name='result',
            name='noi',
            field=models.IntegerField(default=0, verbose_name='net Operating Income'),
        ),
        migrations.AlterField(
            model_name='result',
            name='property_value',
            field=models.IntegerField(default=0, verbose_name='property Value'),
        ),
    ]
