# Generated by Django 2.0.5 on 2018-08-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_auto_20180809_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='id',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_id',
            field=models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
