# Generated by Django 2.0.5 on 2018-08-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_auto_20180809_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caprate',
            name='id',
        ),
        migrations.AddField(
            model_name='caprate',
            name='cap_rate_id',
            field=models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_id',
            field=models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
