# Generated by Django 2.0.5 on 2018-08-10 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_auto_20180809_2034'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rent',
            unique_together={('address', 'unit_number')},
        ),
    ]
