# Generated by Django 2.0.5 on 2018-08-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0016_auto_20180810_0212'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rent',
            unique_together={('address', 'unit_number', 'vacancy', 'bedrooms', 'bathrooms')},
        ),
    ]
