# Generated by Django 2.0.5 on 2018-08-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0017_auto_20180811_1729'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rent',
            unique_together={('address', 'unit_number')},
        ),
    ]
