# Generated by Django 2.0.5 on 2018-08-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0018_auto_20180811_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100, verbose_name='street'),
        ),
    ]
